### ISSUE TITLE
How to query data through android

### ISSUE THREAD

**Issue by superdiazzz** [flamelink/flamelink-android-sdk#1]
I created apps in Android and trying to use flamelink as my CMS alternate way. But i still don't understand when faced up problem in client side. I Knew we can insert data through flamelink easily, but how to query these data from android. 

I have created two schema, suppose they are 'product' and 'seller'. When i creating item 'product' these item will store in same folder with 'seller' (it will stored in fl_content folder in firestore). I knew, actually am new in noSQL(i used to use Related DB) but how to query only for product and only for seller in this case?  Please help

**Comment by dewetvdm** [comment]
Hi @superdiazzz 

I have moved your issue to the flamelink-android-sdk for further details.

To better help you, which Database are you using? Realtime Database or Cloud Firestore?

In the meantime, you can have a look at the following:

For querying data form the Realtime DB you can see these docs
https://firebase.google.com/docs/database/android/read-and-write
The Flamelink Android SDK currently only supports the Realtime Database, you can use this should you want to.

For querying data from Cloud Firestore you can follow these docs
https://firebase.google.com/docs/firestore/query-data/get-data

**Comment by superdiazzz** [comment]
Hi @dewetvdm , am using Firestore. There no sdk for it?

**Comment by gitdubz** [comment]
That is correct, we do not have an SDK for CF yet. 
You can tr to reach out on community support on slack(https://flamelink.io/slack) to see if anyone can help you in addition to the documentation provided by Firebase itself.

**Comment by dewetvdm** [comment]
Closing this - this will be resolved when support for CF is implemented on the SDK
